### ISSUE TITLE
Build Error + Requirements

### ISSUE THREAD

**Issue by Smaltin** [yilmaz0734/Spotify-COVER-IMAGE-DOWNLOADER#1]
I'd like to start off with requesting you add a requirements.txt like [this.](https://github.com/yilmaz0734/Spotify-COVER-IMAGE-DOWNLOADER/files/6085256/requirements.txt)

I didn't have the cx-Freeze library so it threw a bunch of errors, this could've been avoided by providing a requirements.txt.

Also, I noticed you renamed your UI file to "application.ui". On line 14 you need to rename `uygulamam.ui` to `application.ui`.

**Comment by yilmaz0734** [comment]
> I'd like to start off with requesting you add a requirements.txt like [this.](https://github.com/yilmaz0734/Spotify-COVER-IMAGE-DOWNLOADER/files/6085256/requirements.txt)
> 
> I didn't have the cx-Freeze library so it threw a bunch of errors, this could've been avoided by providing a requirements.txt.
> 
> Also, I noticed you renamed your UI file to "application.ui". On line 14 you need to rename `uygulamam.ui` to `application.ui`.

Hello sir, do you think is it okey now? I added the requirements.txt and solved the other issue. Thanks!

**Comment by Smaltin** [comment]
Everything looks great, thanks!
